/*
  Offer Entity
  An Offer Entity is nearly the same as an Order. But while an Order is generated
  by a webhook from P2WDB, the Offer Entity is created internally. It is used
  to track Order generated by this application.

  The Offer tracks the hdIndex address used to hold tokens or BCH for sale.
*/
class Offer {
  validate (data) {
    // Input Validation
    // if (!entry || typeof entry !== "string") {
    //   throw new Error("Property 'entry' must be a string!");
    // }
    // if (!description || typeof description !== "string") {
    //   throw new Error("Property 'description' must be a string!");
    // }
    // if (!slpAddress || typeof slpAddress !== "string") {
    //   throw new Error("Property 'slpAddress' must be a string!");
    // }
    // if (!signature || typeof signature !== "string") {
    //   throw new Error("Property 'signature' must be a string!");
    // }
    // if (!category || typeof category !== "string") {
    //   throw new Error("Property 'category' must be a string!");
    // }

    const offerData = data

    return offerData
  }
}

module.exports = Offer
